language: android
sudo: required
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra
script: ./gradlew clean assemble test uploadArchives
before_install:
- openssl aes-256-cbc -K $encrypted_06e1de1f06bd_key -iv $encrypted_06e1de1f06bd_iv
  -in gradle.properties.enc -out gradle.properties -d
